import '@/css/login.css'

import { ToastContainer, toast } from 'react-toastify';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}

        <ToastContainer />
      </body>

    </html>
  )
}
